[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = "Shougo/deoplete.nvim"
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]] # 各言語の補完
repo = "Shougo/neco-syntax"

